import type { PuzzleDefinition } from "@/types/content";

export const puzzles: Record<string, PuzzleDefinition> = {
  "insertion-sort-budget": {
    engine: "arrayops",
    level: {
      id: "insertion-sort-budget",
      goal: "sorted",
      startValues: [42, 17, 93, 8, 61, 30],
      budget: 24,
      hiddenUntilProbed: false,
      allowedOperations: ["compare", "swap"],
    },
  },
  "binary-search-budget": {
    engine: "arrayops",
    level: {
      id: "binary-search-budget",
      goal: "findTarget",
      startValues: [4, 9, 15, 22, 28, 33, 41, 47, 55, 60, 68, 74, 81, 89, 95, 99],
      budget: 4,
      target: 95,
      hiddenUntilProbed: true,
      allowedOperations: ["probe"],
    },
  },
  "notification-coupling": {
    engine: "blueprint",
    level: {
      id: "notification-coupling",
      responsibilities: [
        { id: "total", label: "Add up the order total", tags: ["pricing"] },
        { id: "discount", label: "Apply the discount code", tags: ["pricing"] },
        { id: "receipt-email", label: "Email the receipt", tags: ["messaging"] },
        { id: "driver-sms", label: "Text the driver", tags: ["messaging"] },
        { id: "push-alert", label: "Push a delivery alert", tags: ["messaging"] },
        { id: "route", label: "Pick the delivery route", tags: ["logistics"] },
        { id: "eta", label: "Work out the arrival time", tags: ["logistics"] },
      ],
      startBlueprints: [
        { id: "order", name: "Order", responsibilityIds: ["total", "discount", "receipt-email"] },
        { id: "delivery", name: "Delivery", responsibilityIds: ["route", "driver-sms"] },
        { id: "customer", name: "Customer", responsibilityIds: ["push-alert", "eta"] },
      ],
      dependencies: [{ dependentId: "delivery", dependencyId: "order" }],
      changeRequests: [
        { id: "swap-provider", label: "Switch to a new messaging provider", tag: "messaging" },
        { id: "new-tax-rule", label: "New regional tax rule", tag: "pricing" },
      ],
      targetBlastRadius: 2,
      spareBlueprintNames: ["Messenger"],
    },
  },
  "open-closed-shipping": {
    engine: "blueprint",
    level: {
      id: "open-closed-shipping",
      responsibilities: [
        { id: "address", label: "Check the delivery address", tags: ["address"] },
        { id: "bike-rate", label: "Rate for bike courier", tags: ["shipping-rate"] },
        { id: "van-rate", label: "Rate for van", tags: ["shipping-rate"] },
        { id: "air-rate", label: "Rate for air freight", tags: ["shipping-rate"] },
        { id: "invoice", label: "Build the invoice", tags: ["billing"] },
        { id: "ledger", label: "Post to the ledger", tags: ["billing"] },
        { id: "track", label: "Track the parcel", tags: ["tracking"] },
      ],
      startBlueprints: [
        {
          id: "checkout",
          name: "Checkout",
          responsibilityIds: ["address", "bike-rate", "van-rate", "invoice"],
        },
        { id: "freight", name: "Freight", responsibilityIds: ["air-rate", "track"] },
        { id: "finance", name: "Finance", responsibilityIds: ["ledger"] },
      ],
      dependencies: [
        { dependentId: "finance", dependencyId: "checkout" },
        { dependentId: "freight", dependencyId: "checkout" },
      ],
      changeRequests: [
        { id: "add-drone", label: "Add a drone delivery rate", tag: "shipping-rate" },
        { id: "vat-change", label: "Change how VAT lands on invoices", tag: "billing" },
      ],
      targetBlastRadius: 1,
      spareBlueprintNames: ["RateBook"],
    },
  },
  "read-scaling-spike": {
    engine: "traffic",
    level: {
      id: "read-scaling-spike",
      arrivalsPerTick: [200, 220, 260, 900, 950, 900, 400, 240, 200, 200],
      readShare: 0.9,
      appCapacityPerServer: 250,
      databaseWriteCapacity: 80,
      databaseReadCapacity: 170,
      replicaReadCapacity: 250,
      cacheHitRate: 0.75,
      queueDepthPerUnit: 200,
      budget: 8,
      maxDropRate: 0.02,
      baseline: { appServer: 1, cache: 0, readReplica: 0, queue: 0 },
      available: [
        {
          kind: "appServer",
          label: "App server",
          description: "Handles 250 requests a tick. Stateless, so copies scale linearly.",
          costPerUnit: 2,
          maxUnits: 4,
        },
        {
          kind: "cache",
          label: "Cache",
          description: "Answers 75% of read traffic before it reaches the app tier.",
          costPerUnit: 2,
          maxUnits: 1,
        },
        {
          kind: "readReplica",
          label: "Read replica",
          description: "Adds 250 reads a tick of database capacity. Writes still go to the leader.",
          costPerUnit: 3,
          maxUnits: 2,
        },
        {
          kind: "queue",
          label: "Queue",
          description: "Holds 200 overflow requests for the next tick instead of dropping them.",
          costPerUnit: 1,
          maxUnits: 2,
        },
      ],
    },
  },
  "write-bottleneck": {
    engine: "traffic",
    level: {
      id: "write-bottleneck",
      arrivalsPerTick: [300, 320, 340, 700, 720, 700, 340, 300],
      readShare: 0.2,
      appCapacityPerServer: 250,
      databaseWriteCapacity: 340,
      databaseReadCapacity: 400,
      replicaReadCapacity: 250,
      cacheHitRate: 0.75,
      queueDepthPerUnit: 300,
      budget: 8,
      maxDropRate: 0.03,
      baseline: { appServer: 1, cache: 0, readReplica: 0, queue: 0 },
      available: [
        {
          kind: "appServer",
          label: "App server",
          description: "Handles 250 requests a tick.",
          costPerUnit: 2,
          maxUnits: 4,
        },
        {
          kind: "cache",
          label: "Cache",
          description: "Answers 75% of read traffic. Only 20% of this workload is reads.",
          costPerUnit: 2,
          maxUnits: 1,
        },
        {
          kind: "readReplica",
          label: "Read replica",
          description: "Adds read capacity only. The read path already has headroom here.",
          costPerUnit: 3,
          maxUnits: 2,
        },
        {
          kind: "queue",
          label: "Queue",
          description: "Holds 300 overflow requests for the next tick. Smooths spikes, adds delay.",
          costPerUnit: 1,
          maxUnits: 2,
        },
      ],
    },
  },
  "linear-separator": {
    engine: "boundary",
    mode: "line",
    level: {
      id: "linear-separator",
      trainingPoints: [
        { x: -7, y: -5, label: 0 },
        { x: -6, y: -2, label: 0 },
        { x: -4, y: -6, label: 0 },
        { x: -3, y: -1, label: 0 },
        { x: -5, y: 1, label: 0 },
        { x: -8, y: 0, label: 0 },
        { x: 2, y: 4, label: 1 },
        { x: 4, y: 2, label: 1 },
        { x: 6, y: 6, label: 1 },
        { x: 3, y: 7, label: 1 },
        { x: 7, y: 3, label: 1 },
        { x: 5, y: 0, label: 1 },
      ],
      testPoints: [
        { x: -6, y: -4, label: 0 },
        { x: -2, y: -3, label: 0 },
        { x: -7, y: 2, label: 0 },
        { x: 3, y: 3, label: 1 },
        { x: 6, y: 1, label: 1 },
        { x: 4, y: 6, label: 1 },
      ],
      targetTestAccuracy: 1,
      neighbourOptions: [1, 3, 5, 7],
    },
  },
  "overfitting-neighbours": {
    engine: "boundary",
    mode: "neighbours",
    level: {
      id: "overfitting-neighbours",
      trainingPoints: [
        { x: 2.3, y: 0.7, label: 1 },
        { x: 0.5, y: 2.3, label: 1 },
        { x: -1.8, y: 1.6, label: 1 },
        { x: -2.3, y: -0.7, label: 1 },
        { x: -0.5, y: -2.3, label: 1 },
        { x: 1.8, y: -1.6, label: 1 },
        { x: 0, y: 0, label: 1 },
        { x: 7.1, y: 1.1, label: 0 },
        { x: 5.6, y: 4.5, label: 0 },
        { x: 2.6, y: 6.7, label: 0 },
        { x: -1.1, y: 7.1, label: 0 },
        { x: -4.5, y: 5.6, label: 0 },
        { x: -6.7, y: 2.6, label: 0 },
        { x: -7.1, y: -1.1, label: 0 },
        { x: -5.6, y: -4.5, label: 0 },
        { x: -2.6, y: -6.7, label: 0 },
        { x: 1.1, y: -7.1, label: 0 },
        { x: 4.5, y: -5.6, label: 0 },
        { x: 6.7, y: -2.6, label: 0 },
        { x: 1.5, y: 1.2, label: 0 },
        { x: -5.4, y: 2.8, label: 1 },
      ],
      testPoints: [
        { x: 1.3, y: 2.6, label: 1 },
        { x: -2.1, y: 2, label: 1 },
        { x: -2.6, y: -1.3, label: 1 },
        { x: 0.5, y: -2.9, label: 1 },
        { x: 2.9, y: -0.5, label: 1 },
        { x: 4.1, y: 5.2, label: 0 },
        { x: -1.5, y: 6.4, label: 0 },
        { x: -6, y: 2.8, label: 0 },
        { x: -5.9, y: -2.9, label: 0 },
        { x: -1.5, y: -6.4, label: 0 },
        { x: 4.1, y: -5.2, label: 0 },
        { x: 6.6, y: 0, label: 0 },
        { x: 1.7, y: 1.4, label: 1 },
        { x: 1.2, y: 1.6, label: 1 },
        { x: -6.4, y: 3.2, label: 0 },
      ],
      targetTestAccuracy: 0.95,
      neighbourOptions: [1, 3, 5, 9, 13],
    },
  },
};

export function getPuzzle(puzzleId: string): PuzzleDefinition {
  const puzzle = puzzles[puzzleId];
  if (!puzzle) {
    throw new Error(`No puzzle registered under "${puzzleId}".`);
  }
  return puzzle;
}
